### ISSUE TITLE
Duel room streaks at 10/20/30 not adding jewels

### ISSUE THREAD

**Issue by suhbruh** [open-gunz/ogz-source#59]
When playing duel mode, you know the jewels that show up under your HP/AP bar as you get streaks? The large jewel you get at 10 streak does not show up on and onwards (same with 20), but comes back after 15 streak (same with 25). Here are pics to illustrate what I mean:

8 streak:
https://cdn.discordapp.com/attachments/489831263906037771/696408469368209509/GunZ038.png

10 streak:
https://cdn.discordapp.com/attachments/489831263906037771/696408487751581796/GunZ039.png

11 streak:
https://cdn.discordapp.com/attachments/489831263906037771/696408460312707132/GunZ040.png

15 streak:
https://cdn.discordapp.com/attachments/489831263906037771/696408466981519390/GunZ041.png

18 streak:
https://cdn.discordapp.com/attachments/489831263906037771/696408456076197949/GunZ043.png

20 streak:
https://cdn.discordapp.com/attachments/489831263906037771/696408449474625546/GunZ044.png

21 streak:
https://cdn.discordapp.com/attachments/489831263906037771/696408406621290526/GunZ045.png

25 streak:
https://cdn.discordapp.com/attachments/489831263906037771/696408449042481162/GunZ046.png

27 streak:
https://cdn.discordapp.com/attachments/489831263906037771/696408425357246494/GunZ047.png

Bug first described by Ennui to SuhBruh.

**Comment by mhs02** [comment]
fixed
https://github.com/open-gunz/ogz-source/pull/87
