### ISSUE TITLE
AccountItem missing table and crashing MatchServer

### ISSUE THREAD

**Issue by Iazzetta** [open-gunz/ogz-source#82]
I don't know why yet when I crate AccountItem table and player open Storage Bank Matchserver Crashs without any log.
GetAccountItemInfo its a good start

**Comment by mhs02** [comment]
maybe your table is incorrect.
if your using sqlite

```cpp
exec("CREATE TABLE IF NOT EXISTS AccountItem(AIID integer PRIMARY KEY NOT NULL, "
		"AID integer NOT NULL, "
		"ItemID integer NOT NULL, "
		"RentDate datetime , "
		"RentHourPeriod integer, "
		"Cnt integer)");

```

this was taken from igunz src itself

are they similiar?

**Comment by Iazzetta** [comment]
I created the RentDate as Integer (based on the CharacterItem table). But even creating the table with this command that you passed, when changing from equipment to storage it crash

**Comment by Iazzetta** [comment]
I fixed this with simple modifications:

**SQLiteDatabase.cpp** -> **bool SQLiteDatabase::GetAccountItemInfo**

change
```
int NodeCount;
int ExpiredItemCount;
```
to
```
int NodeCount = 0;
int ExpiredItemCount = 0;
```
