### ISSUE TITLE
Why isnt showing ugrade colors in lobby/stage?

### ISSUE THREAD

**Issue by Iazzetta** [open-gunz/ogz-source#83]
Ok I took a long time to fix and I cant. I can see the pItem->SetColor(color); in ZPlayerListBox when we add player but the color just show in tab and chat. Any fix from igunz?

**Comment by mhs02** [comment]
Good to see you again!

I fixed this in igunz by porting over some changes from 1.5 source for the player listbox item class, as well as some additional changes in its Draw function.

Take a look at your SetColor methods. This method is an override from the inherited class, and likely needs to be changed.

Take a look at the player listbox draw function. You may need to pull the user grades color, and set it.

Unfortunately, I am not available until this weekend.
If you haven't figured it out by then, I will push up the fix.
Sorry if I'm not very helpful right now, I am on my mobile.

Cheers.

**Comment by Iazzetta** [comment]
ok I hate c++ #84
