### ISSUE TITLE
[FIX] ZConfiguration PrimaryWeapon not saving

### ISSUE THREAD

**Issue by Iazzetta** [open-gunz/ogz-source#85]
When you change primaryweapon (late dash config), not saving. This is the fix for it. (from 1.5)

Search for **bool ZConfiguration::LoadConfig(const char* szFileName)** and change:

```
actionKeyElement.GetAttribute(&nKey,"alt",-1);
    if(nKey!=-1)
```
to:
```
actionKeyElement.GetAttribute(&nKey,"alt",-2);
    if(nKey!=-2)
```

Comment this:

```
_ASSERT(ZACTION_COUNT==sizeof(DefaultActionKeys)/sizeof(ZACTIONKEYDESCRIPTION));
```

----------

in **src/Gunz/ZInput.h** go to **bool IsActionKeyDown(int nActionID)** and comment:
```
_ASSERT(FALSE);	// 0 ~ ACTIONKEYMAP_IDCOUNT-1 ���̰��̿��� �Ѵ�.
```

 in **src/Gunz/ZInput.h** go to **bool WasActionKeyDownLast(int nActionID)** and comment:
```
_ASSERT(FALSE);	// 0 ~ ACTIONKEYMAP_IDCOUNT-1 ���̰��̿��� �Ѵ�.
```

I think it's just that. As I made many changes today I don't remember if it was just that.

**Comment by mhs02** [comment]
Iirc, _ASSERT is only executed in Debug builds.
They should not get executed in any of the Release builds(including RelWithDebugInfo).
